{% set name = "pandas-stubs" %}
{% set version = "1.4.3.220702" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1a8c22f096655f25c2cf18258b2cdecd339da9bc50d251060604cb67b7958050

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
    - typing_extensions >=4.2
  run:
    - python >=3.8
    - typing_extensions >=4.2

test:
  commands:
    - test -f $SP_DIR/pandas-stubs/_typing.pyi  # [unix]
    - if not exist %SP_DIR%\\pandas-stubs\\_typing.pyi exit 1  # [win]


about:
  home: https://github.com/pandas-dev/pandas-stubs
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Collection of Pandas stub files
  description: |
    Collection of Pandas stub files supported by the pandas team
  doc_url: https://github.com/pandas-dev/pandas-stubs
  dev_url: https://github.com/pandas-dev/pandas-stubs

extra:
  recipe-maintainers:
    - Dr-Irv
    - joannasendorek
    - zkrolikowski-vl
    - hpomorski
