{% set name = "pandas-stubs" %}
{% set version = "2.1.4.231227" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_stubs-{{ version }}.tar.gz
  sha256: 3ea29ef001e9e44985f5ebde02d4413f94891ef6ec7e5056fb07d125be796c23

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  # s390x is missing types-pytz
  skip: True  # [py<39 or s390x]

requirements:
  host:
    - python
    - pip
    - poetry-core
    - wheel
  run:
    - python
    - types-pytz >=2022.1.1
    - numpy >=1.26  # [py<313]

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/pandas-stubs/_typing.pyi  # [unix]
    - if not exist %SP_DIR%\\pandas-stubs\\_typing.pyi exit 1  # [win]

about:
  home: https://github.com/pandas-dev/pandas-stubs
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Collection of Pandas stub files
  description: |
    Collection of Pandas stub files supported by the pandas team
  doc_url: https://github.com/pandas-dev/pandas-stubs # Documentation is a work-in-progress.
  dev_url: https://github.com/pandas-dev/pandas-stubs

extra:
  recipe-maintainers:
    - twoertwein
    - Dr-Irv
  skip-lints:
    - missing_imports_or_run_test_py
