{% set name = "pandas-stubs" %}
{% set version = "3.0.0.260204" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace("-", "_")}}-{{ version }}.tar.gz
  sha256: bf9294b76352effcffa9cb85edf0bed1339a7ec0c30b8e1ac3d66b4228f1fbc3

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - numpy >=1.23.5

test:
  requires:
    - pip
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - test -f $SP_DIR/pandas-stubs/_typing.pyi  # [unix]
    - if not exist %SP_DIR%\\pandas-stubs\\_typing.pyi exit 1  # [win]

about:
  home: https://github.com/pandas-dev/pandas-stubs
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Collection of Pandas stub files
  description: |
    These are public type stubs for pandas, following the convention of
    providing stubs in a separate package, as specified in PEP 561.
    The stubs cover the most typical use cases of pandas. In general,
    these stubs are narrower than what is possibly allowed by pandas,
    but follow a convention of suggesting best recommended practices for using pandas.
  doc_url: https://github.com/pandas-dev/pandas-stubs/blob/main/README.md
  dev_url: https://github.com/pandas-dev/pandas-stubs

extra:
  recipe-maintainers:
    - twoertwein
    - Dr-Irv
  skip-lints:
    - missing_imports_or_run_test_py
