{% set name = "pandas-stubs" %}
{% set version = "1.5.3.230203" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # As of 2/13/2023 archive was unavailable on PyPi
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/pandas-dev/pandas-stubs/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 16dbefc3c2d8fb2eed4970bcb74a8746e7520e34477a7b9b69afef00ec80ae83

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps
  skip: True  # [py<38]

requirements:
  host:
    - python
    - pip
    - poetry
    - setuptools
    - wheel
  run:
    - python
    - types-pytz >=2022.1.1

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/pandas-stubs/_typing.pyi  # [unix]
    - if not exist %SP_DIR%\\pandas-stubs\\_typing.pyi exit 1  # [win]

about:
  home: https://github.com/pandas-dev/pandas-stubs
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Collection of Pandas stub files
  description: |
    Collection of Pandas stub files supported by the pandas team
  doc_url: https://github.com/pandas-dev/pandas-stubs # Documentation is a work-in-progress.
  dev_url: https://github.com/pandas-dev/pandas-stubs

extra:
  recipe-maintainers:
    - twoertwein
    - Dr-Irv
