{% set name = "pandas-stubs" %}
{% set version = "2.2.3.250308" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandas_stubs-{{ version }}.tar.gz
  sha256: 3a6e9daf161f00b85c83772ed3d5cff9522028f07a94817472c07b91f46710fd

build:
  number: 0
  # s390x is missing types-pytz
  skip: True  # [py<310 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.0.0
  run:
    - python
    - types-pytz >=2022.1.1
    - numpy >=1.23.5

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/pandas-stubs/_typing.pyi  # [unix]
    - if not exist %SP_DIR%\\pandas-stubs\\_typing.pyi exit 1  # [win]

about:
  home: https://github.com/pandas-dev/pandas-stubs
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Collection of Pandas stub files
  description: |
    Collection of Pandas stub files supported by the pandas team
  doc_url: https://github.com/pandas-dev/pandas-stubs # Documentation is a work-in-progress.
  dev_url: https://github.com/pandas-dev/pandas-stubs

extra:
  recipe-maintainers:
    - twoertwein
    - Dr-Irv
  skip-lints:
    - missing_imports_or_run_test_py
